// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1dYDVVTMZgOH1XTU7gbrDReDCVeYFFPM',
    appId: '1:779475431677:web:b2096be4ae1daefe228e94',
    messagingSenderId: '779475431677',
    projectId: 'nostra-dev',
    authDomain: 'nostra-dev.firebaseapp.com',
    storageBucket: 'nostra-dev.appspot.com',
    measurementId: 'G-896Z0RH7WV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWGIHqb_1zHWEiCOhjKlfOT3OFbDTlu4Q',
    appId: '1:779475431677:android:de9b4df9011b327a228e94',
    messagingSenderId: '779475431677',
    projectId: 'nostra-dev',
    storageBucket: 'nostra-dev.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWVmncxznzCMv-A2wPHTazW844vSu2RZY',
    appId: '1:779475431677:ios:ada2814f456a8315228e94',
    messagingSenderId: '779475431677',
    projectId: 'nostra-dev',
    storageBucket: 'nostra-dev.appspot.com',
    iosBundleId: 'com.example.nostraApp.RunnerTests',
  );
}
