// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseOptionsStg {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDubMW-845OYAFjx5t6X8e3bQ0Ur4afAB8',
    appId: '1:683765148604:web:b4a957941d944155db99b9',
    messagingSenderId: '683765148604',
    projectId: 'nostra-stg',
    authDomain: 'nostra-stg.firebaseapp.com',
    storageBucket: 'nostra-stg.appspot.com',
    measurementId: 'G-RPZPHGML3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH9pSEwRGfwI9jIFD5srv-J95A4G5lwlc',
    appId: '1:683765148604:android:c9a578950f55c619db99b9',
    messagingSenderId: '683765148604',
    projectId: 'nostra-stg',
    storageBucket: 'nostra-stg.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtuzJVvhcE1q3BauMisTIs9h58RGTg_r0',
    appId: '1:683765148604:ios:aab0150c56f2d014db99b9',
    messagingSenderId: '683765148604',
    projectId: 'nostra-stg',
    storageBucket: 'nostra-stg.appspot.com',
    iosBundleId: 'com.example.nostraApp.RunnerTests',
  );
}
